import jsPDF from "jspdf";

/**
 * Generate a simple, readable PDF report from a diagnosis result object.
 */
export function generateDiagnosisPDF(diagnosis, meta = {}) {
  const doc = new jsPDF();
  const margin = 15;
  let y = 20;

  const addLine = (text, { size = 11, bold = false, color = [31, 41, 55], gap = 7 } = {}) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, 180);
    lines.forEach((line) => {
      if (y > 280) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, margin, y);
      y += gap;
    });
  };

  doc.setFillColor(5, 150, 105);
  doc.rect(0, 0, 210, 14, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("KrishiMitra AI — Crop Diagnosis Report", margin, 9.5);
  y = 24;

  addLine(`Date: ${new Date().toLocaleString()}`, { size: 9, color: [107, 114, 128], gap: 6 });
  if (meta.cropType) addLine(`Crop: ${meta.cropType}`, { size: 9, color: [107, 114, 128], gap: 6 });
  y += 2;

  addLine(diagnosis.diseaseName || "N/A", { size: 17, bold: true, color: [6, 78, 59], gap: 9 });
  addLine(
    `Severity: ${diagnosis.severity || "N/A"}   |   Confidence: ${diagnosis.confidencePercentage ?? "N/A"}%`,
    { size: 11, color: [217, 119, 6], gap: 9 }
  );

  const section = (title, items) => {
    if (!items || (Array.isArray(items) && items.length === 0)) return;
    addLine(title, { size: 13, bold: true, color: [6, 78, 59], gap: 8 });
    const arr = Array.isArray(items) ? items : [items];
    arr.forEach((item) => addLine(`• ${item}`, { size: 10.5, gap: 6 }));
    y += 3;
  };

  section("Symptoms", diagnosis.symptoms);
  section("Organic Treatment", diagnosis.treatment?.organic);
  section("Chemical Treatment", diagnosis.treatment?.chemical);
  section("Preventive Measures", diagnosis.preventiveMeasures);
  section("Immediate Next Steps", diagnosis.immediateNextSteps);
  section("When to Consult an Expert", diagnosis.consultExpertIf);
  if (diagnosis.limitations) section("Limitations", diagnosis.limitations);

  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text(
    "Generated by KrishiMitra AI — Always consult a local agricultural expert before applying chemical treatments.",
    margin,
    292
  );

  doc.save(`krishimitra-diagnosis-${Date.now()}.pdf`);
}
